"""MQTT boundary for ESP32 vision nodes."""

from vision_hub.mqtt.client import MqttClient, MqttConnectionConfig
from vision_hub.mqtt.messages import (
    ImageChunkMessage,
    ImageDoneMessage,
    ImageMetaMessage,
    IncomingMqttMessage,
    NodeEventMessage,
    NodePresenceMessage,
    NodeReplyMessage,
    NodeRuntimeConfigPatch,
    NodeStatus,
    NodeHeartbeatMessage,
    OutgoingCommand,
    PayloadError,
    build_broadcast_capture_command,
    build_broadcast_config_command,
    build_broadcast_ping_command,
    build_broadcast_reboot_command,
    build_capture_command,
    build_config_command,
    build_ping_command,
    build_reboot_command,
    parse_incoming_message,
)
from vision_hub.mqtt.topics import (
    CommandName,
    IncomingTopic,
    IncomingTopicKind,
    TopicError,
    build_broadcast_command_topic,
    build_node_command_topic,
    parse_incoming_topic,
)

__all__ = [
    "CommandName",
    "ImageChunkMessage",
    "ImageDoneMessage",
    "ImageMetaMessage",
    "IncomingMqttMessage",
    "IncomingTopic",
    "IncomingTopicKind",
    "MqttClient",
    "MqttConnectionConfig",
    "NodeEventMessage",
    "NodeHeartbeatMessage",
    "NodePresenceMessage",
    "NodeReplyMessage",
    "NodeRuntimeConfigPatch",
    "NodeStatus",
    "OutgoingCommand",
    "PayloadError",
    "TopicError",
    "build_broadcast_command_topic",
    "build_broadcast_capture_command",
    "build_broadcast_config_command",
    "build_broadcast_ping_command",
    "build_broadcast_reboot_command",
    "build_capture_command",
    "build_config_command",
    "build_node_command_topic",
    "build_ping_command",
    "build_reboot_command",
    "parse_incoming_message",
    "parse_incoming_topic",
]
